### ISSUE TITLE
Public Docs for Epochs and Staking Collection

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-core-contracts#208]
### Issue To Be Solved

Need docs to share with the public and partners about epochs and staking collection before we launch them

### Suggest A Solution

- [x] Outline in a feature branch in `onflow/flow`
- [x] Epochs Technical Overview, scripts, and events
- [x] Update staking auction technical overview, scripts, and events
- [x] QC Technical Overview, scripts, and events
- [x] DKG Technical Overview, scripts, and events
- [x] Updated staking instructions to use the staking collection
- [x] Update old staking instructions

cc @jordanschalm @JeffreyDoyle @franklywatson

**Comment by franklywatson** [comment]
Overall not many issue or feedback to make. A few nits below: 

In https://flow-docs-git-epoch-org-onflow.vercel.app/staking/

Sentence "These processes are called Cluser Quorum Certificate Generation (QC), and Distributed Key Generation (DKG)" has cluster spelt wrong. 

Epochs link in the same page (paragraph above Rewards title) links to https://flow-docs-git-epoch-org-onflow.vercel.app/staking/epochs/ (currently 404s). Not sure if that will be fixed by deployment or not. Same for the rewards link below that


In https://flow-docs-git-epoch-org-onflow.vercel.app/staking/staking-scripts-events/
the sentence "Emitted by FlowIDTableStaking.Admin.moveTokens() at the end of an epoch if a node operator's staked tokens are being unstaked in response to a request from the node operator to do so" could probably drop the "to do so" at the end. 

Similar comment on "Emitted by FlowIDTableStaking.Admin.moveTokens() at the end of an epoch if a delegator's staked tokens are being unstaked in response to a request from the delegator to do so."

let me know when the TODOs are added and will do a follow up review
