### ISSUE TITLE
Epoch Public Technical Docs, Scripts, and Events

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-core-contracts#210]
# Summary

Transfer the important parts of the [Epoch Notion Docs](https://www.notion.so/dapperlabs/Epochs-412af292863e4d8f95bf2fcd14e36612) to the public Docs site

# Tasks

- [x] Epoch aware protocol state
- [x] Epoch Preparation Protocol
- [x] Service events
- [ ] Machine Accounts
- [x] QC and DKG summary
- [ ] Smart contract architecture
- [x] Scripts to query epoch info and metadata
