### ISSUE TITLE
Upgrade FlowFees and FlowIDTableStaking on all the networks

### ISSUE THREAD

**Issue by joshuahannan** [onflow/flow-core-contracts#236]
# Summary

In #235, we made changes to the two contracts to use the tokens collected from transaction fees to pay a portion of staking rewards. We need to apply these updates to the contracts on the various networks.

# Tasks

- [ ] Upgrade FlowFees and FlowIDTableStaking on Canary
- [ ] Upgrade FlowFees and FlowIDTableStaking on Testnet
- [ ] Upgrade FlowFees and FlowIDTableStaking on Mainnet
